name: gradle-ci
on: [ push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build artifacts
      run: chmod +x ./gradlew; ./gradlew build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: BYG-${{ steps.ref.outputs.branch }}
        # Filter built files to disregard -sources and -dev, and leave only the minecraft-compatible jars.
        path: build/libs/*[0-9].jar
